config/routes.rb
Whiteboard::Application.routes.draw do
  resources :items, only: :create
  resources :sessions, only: [:create, :destroy]

  resources :standups, shallow: true do
    resources :items, only: :new
    resources :items do
      collection do
        get 'presentation'
      end
    end

    resources :posts do
      member do
        put 'send_email'
        put 'post_to_blog'
        put 'archive'
      end

      collection do
        get 'archived'
      end

    end
  end

  match '/auth/saml/callback', to: 'sessions#create', via: [:get, :post]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  root to: 'standups#last_or_index'
end

app/models/standup.rb
require "ipaddr"

class Standup < ActiveRecord::Base
  TIME_FORMAT = /(\d{1,2}):(\d{2})\s*(am|pm)/i

  attr_accessible :title, :to_address, :subject_prefix, :closing_message, :time_zone_name, :start_time_string, :image_urls, :image_days
  serialize :image_days

  has_many :items, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :title, presence: true
  validates :to_address, presence: true
  validates :start_time_string, format: {with: TIME_FORMAT, message: "should be in the format: 9:00am"}

  def date_today
    time_zone.now.to_date
  end

  def date_tomorrow
    date_today + 1.day
  end

  def time_zone
    ActiveSupport::TimeZone.new(time_zone_name)
  end

  def next_standup_date
    standup_time = standup_time_today

    standup_time += 1.day if finished_today

    standup_time
  end

  def time_zone_name_iana
    ActiveSupport::TimeZone.find_tzinfo(self.time_zone_name).identifier
  end

  def finished_today
    standup_time_today < time_zone.now
  end

  private

  def standup_time_today
    hours, minutes = hour_of_standup
    time_zone.now.beginning_of_day + hours.hours + minutes.minutes
  end

  def hour_of_standup
    matches = start_time_string.match(Standup::TIME_FORMAT)
    hours, minutes = matches[1].to_i, matches[2].to_i
    hours += 12 if hours != 12 && matches[3] =~ /pm/i

    [hours, minutes]
  end
end

app/controllers/standups_controller.rb
class StandupsController < ApplicationController
  before_filter :load_standup, only: [:edit, :show, :update, :destroy]
  around_filter :standup_timezone, only: [:edit, :show, :update, :destroy]


  def create
    @standup = Standup.create(params[:standup])

    if @standup.persisted?
      flash[:notice] = "#{@standup.title} Standup successfully created"
      redirect_to @standup
    else
      render 'standups/new'
    end
  end

  def new
    @standup = Standup.new(params[:standup])
  end

  def index
    @standups = Standup.all.sort { |a, b| a.title.downcase <=> b.title.downcase }
  end

  def edit;
  end

  def show
    if @standup
      session[:last_visited_standup] = params[:id]
      respond_to do |format|
        format.html {
          redirect_to standup_items_path(@standup)
        }
        format.json {
          render json: @standup.to_json(:methods => :time_zone_name_iana)
        }
      end
    else
      respond_to do |format|
        format.html {
          flash[:error] = "A standup with the ID #{params[:id]} does not exist."
          redirect_to standups_path
        }
        format.json {
          head :not_found
        }
      end
    end
  end

  def update
    if @standup.update(params[:standup])
      redirect_to @standup
    else
      render 'standups/edit'
    end
  end

  def destroy
    @standup.destroy
    redirect_to standups_path
  end

  def last_or_index
    last_standup_id = session[:last_visited_standup]
    if last_standup_id && Standup.find_by(id: last_standup_id)
      redirect_to standup_path(last_standup_id)
    else
      redirect_to standups_path
    end
  end

  private

  def load_standup
    @standup = Standup.find_by(id: params[:id])
  end

  def standup_timezone(&block)
    return yield unless @standup
    Time.use_zone(@standup.time_zone_name, &block)
  end
end

app/views/standups/_form.html.erb
<%= form_for standup, html: {class: 'form-horizontal'} do |form| %>
    <%= render partial: 'shared/errors',  locals: {model: standup} %>

    <div class='title form-group' style="padding-top: 8px">
      <%= form.label :title, class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.text_field :title, :placeholder => 'Title', :size => nil, :class => "wide" %>
      </div>
    </div>

    <div class='subject_prefix form-group'>
      <%= form.label :subject_prefix, 'Email Subject Prefix', class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.text_field :subject_prefix, :placeholder => 'Email Subject Prefix', :size => nil, :class => "wide" %>
      </div>
    </div>

    <div class='to_address form-group'>
      <%= form.label :to_address, 'Send Email To', class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.text_field :to_address, :placeholder => 'Send Email To (address)', :size => nil, :class => "wide" %>
      </div>
    </div>

    <div class='closing_message form-group'>
      <%= form.label :closing_message, class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.text_field :closing_message, :placeholder => 'Closing Message (optional)', :size => nil, :class => "wide" %>
      </div>
    </div>

    <div class='time_zone form-group'>
      <%= form.label :time_zone_name, 'Time Zone', class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.select :time_zone_name, ActiveSupport::TimeZone.all.map(&:name), :class => "wide" %>
      </div>
    </div>

    <div class='start_time_string form-group'>
      <%= form.label :start_time_string, 'Start Time (ex. 9:06am)', class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.text_field :start_time_string, :class => "wide" %>
      </div>
    </div>

    <div class='image_urls form-group'>
      <%= form.label :image_urls, 'Image URLs (newline separated)', class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.text_area :image_urls, :class => "input-xxlarge", :rows => 8 %>
      </div>
    </div>

    <div class='image_days form-group'>
      <%= form.label :image_days, 'Show image on', class: 'control-label col-sm-2' %>
      <div class="controls col-sm-10">
        <%= form.collection_check_boxes(:image_days, [['Mon', 'M'], ['Tue', 'Tu'], ['Wed', 'W'], ['Thu', 'Th'], ['Fri', 'F']], :first, :last) %>
      </div>
    </div>

    <div class='form-group'>
      <div class="controls col-sm-10">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
<%- end %>

app/views/standups/edit.html.erb
<div class="content-wrapper">
  <div class="standup">
    <div class="block header">
      <h1>Edit Standup</h1>
    </div>

    <%= render 'form', standup: @standup %>

    <%= form_for @standup, method: :delete, html: {class: 'form-horizontal'} do |form| %>
      <div class='control-group'>
        <div class="controls">
          <%= form.submit 'Delete Standup', class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
        </div>
      </div>
    <%- end %>
  </div>
</div>

app/views/standups/index.html.erb
<div class="content-wrapper">
  <div class="standup">
    <div class="block header">
      <h2>Choose a Standup</h2>
    </div>
    <% @standups.each do |standup| %>
      <div class="block">
        <h1><%= link_to standup.title, standup %></h1>
      </div>
    <% end %>
    <div class="block buttons">
      <%= link_to('New Standup'.html_safe, new_standup_path, class: 'btn btn-primary btn-large btn-block') %>
    </div>
  </div>
</div>

app/views/standups/new.html.erb
<div class="content-wrapper">
  <div class="standup">
    <div class="block header">
      <h2>New Standup</h2>
    </div>

    <%= render 'form', standup: @standup %>
  </div>
</div>