config/routes.rb
Whiteboard::Application.routes.draw do
  resources :items, only: :create
  resources :sessions, only: [:create, :destroy]

  resources :standups, shallow: true do
    resources :items, only: :new
    resources :items do
      collection do
        get 'presentation'
      end
    end

    resources :posts do
      member do
        put 'send_email'
        put 'post_to_blog'
        put 'archive'
      end

      collection do
        get 'archived'
      end

    end
  end

  match '/auth/saml/callback', to: 'sessions#create', via: [:get, :post]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  root to: 'standups#last_or_index'
end

app/views/partials/_flash.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <%= flash[:error] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <% if @standup.present? && @standup.persisted? %>
      <%= link_to "#{@standup.title} Whiteboard", standup_items_path(@standup), :class => 'navbar-brand' %>
      <% else %>
        <%= link_to "Whiteboard", standups_path, :class => 'navbar-brand' %>
      <% end %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
    <% if @standup.present? && @standup.persisted? %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle posts" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Current Post", standup_path(@standup) %></li>
            <li><%= link_to "Pending Posts (#{pending_post_count(@standup)})", standup_posts_path(@standup) %></li>
            <li><%= link_to "Archived Posts", archived_standup_posts_path(@standup) %></li>
          </ul>
        </li>
        <li><%= link_to "Preferences", edit_standup_path(@standup) %></li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "All Standups", standups_path %>
        </li>
        <% if session['logged_in'] %>
          <li>
            <%= link_to 'Log Out', '/logout' %>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>