config/routes.rb
Whiteboard::Application.routes.draw do
  resources :items, only: :create
  resources :sessions, only: [:create, :destroy]

  resources :standups, shallow: true do
    resources :items, only: :new
    resources :items do
      collection do
        get 'presentation'
      end
    end

    resources :posts do
      member do
        put 'send_email'
        put 'post_to_blog'
        put 'archive'
      end

      collection do
        get 'archived'
      end

    end
  end

  match '/auth/saml/callback', to: 'sessions#create', via: [:get, :post]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  root to: 'standups#last_or_index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  KINDS = [{name: 'New face', subtitle: ''},
    {name: 'Help', subtitle: ''},
    {name: 'Interesting', subtitle: 'News, Articles, Tools, Best Practices, etc'},
    {name: 'Event', subtitle: ''},
    {name: 'Win', subtitle: 'Use this to announce achievements in line with company goals. Eg. signed client X, incepted project Y, released product Z...'}
  ]

  default_scope { order('date ASC') }

  belongs_to :post
  belongs_to :standup

  validates_inclusion_of :kind, in: KINDS.map { |k| k[:name] }
  validates :standup, presence: true
  validates :title, presence: true
  validate :face_is_in_the_future

  attr_accessible :title, :description, :kind, :public, :post_id, :date, :standup_id, :author

  def self.public
    where(public: true)
  end

  def self.orphans
    where(post_id: nil).where.not(kind: 'Event').where("date >= ? OR kind = 'Help' OR kind = 'Interesting'", Time.zone.today).order("date ASC").group_by(&:kind)
  end

  def self.events_on_or_after(date, standup)
    where(kind: "Event").
      where("standup_id = #{standup.id} OR standup_id IS NULL").
      where("date >= ?", date).
      where(post_id: nil).
      order("date").
      group_by(&:kind)
  end

  def self.for_post(standup)
    where(post_id: nil, bumped: false).
      where("standup_id = #{standup.id} OR standup_id IS NULL").
      where("(kind != 'Event' OR date = ?)", Time.zone.today).
      where("date IS NULL OR date <= ?", Time.zone.today)
  end

  def possible_template_name
    kind && "items/new_#{kind.downcase.gsub(" ", '_')}"
  end

  def relative_date
    case date
    when standup.date_today then
      :today
    when standup.date_tomorrow then
      :tomorrow
    else
      :upcoming
    end
  end

  def self.kinds
    kinds = KINDS.map { |kind| Kind.new(kind[:name], kind[:subtitle]) }
    unless ENV['ENABLE_WINS'] == 'true'
      kinds.delete_if {|kind| kind.name == 'Win'}
    end
    kinds
  end

  private
  def new_face?
    kind == 'New face'
  end

  def face_is_in_the_future
    return unless new_record?
    return unless new_face?
    return unless date?
    return unless date.beginning_of_day < Time.zone.now.beginning_of_day

    errors.add(:base, 'Please choose a date in present or future')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :load_standup
  around_filter :standup_timezone
  respond_to :html, :json

  def create
    @item = Item.new(params[:item])
    if @item.save
      response.headers["Item-Id"]=@item.id.to_s
      redirect_to @item.post ? edit_post_path(@item.post) : standup_path(@item.standup)
    else
      render 'items/new'
    end
  end

  def new
    options = (params[:item] || {}).merge({post_id: params[:post_id], author: session[:username]})
    options.reverse_merge!(date: Time.zone.today)
    @item = @standup.items.build(options)
    render_custom_item_template @item
  end

  def index
    events = Item.events_on_or_after(Time.zone.today, @standup)
    @items = @standup.items.orphans.merge(events)
    respond_with(@items)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to request.referer
  end

  def edit
    @item = Item.find(params[:id])
    render_custom_item_template @item
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(params[:item])
    if @item.save
      redirect_to params[:redirect_to] || @standup
    else
      render_custom_item_template @item
    end
  end

  def presentation
    events = Item.events_on_or_after(Time.zone.today, @standup)
    @items = @standup.items.orphans.merge(events)
    render layout: 'deck'
  end

  private

  def render_custom_item_template(item)
    if item.possible_template_name && template_exists?(item.possible_template_name)
      render item.possible_template_name
    else
      render "items/new"
    end
  end

  def load_standup
    if params[:standup_id].present?
      standup = Standup.find_by(id: params[:standup_id])
    elsif params.fetch(:item, {})[:standup_id].present?
      standup = Standup.find_by(id: params[:item][:standup_id])
    else
      standup = Item.find_by(id: params[:id]).standup
    end

    @standup = StandupPresenter.new(standup)
  end

  def standup_timezone(&block)
    return yield unless @standup
    Time.use_zone(@standup.time_zone_name, &block)
  end
end

app/views/items/_as_html.html.erb
<% Item.kinds.each_with_index do |kind, index| %>
  <% if index % 2 == 0%>
    <div class="row">
  <% end %>
  <div class="<%= kind.name.downcase.tr(' ', '_') %> col-md-6 col-xs-12">
    <div class="block header">
      <h2 class="title"><%= kind.name.pluralize %></h2>
      <%= link_to new_standup_item_path(@standup, post_id: @post.try(:id), 'item[kind]' => kind.name), 'data-kind' => kind.name do %>
        <i class="icon-plus-sign"></i>
      <% end %>
    </div>
    <% if kind.subtitle.present? %>
      <div class="subtitle"><%= kind.subtitle %></div>
    <% end %>
    <% if items[kind.name].present? %>
      <% if kind.name == 'Event' || kind.name == 'New face' %>
        <% items[kind.name].group_by(&:relative_date).each do |group_name, events| %>
          <h4 class="subheader <%= group_name %>"><%= group_name.capitalize %></h4>
          <%= render events %>
        <% end %>
      <% else %>
        <%= render items[kind.name] %>
      <% end %>
    <% end %>
  </div>
  <% if index % 2 == 1 %>
    </div>
  <% end %>
<% end %>

app/views/items/_as_markdown.text.erb
<% Item.kinds.each do |kind| %>
  <% if items[kind.name].present? %>
## <%= kind.name.pluralize.html_safe %>

    <% items[kind.name].each do |item| %>
      <% if item.date.present? %>
### <%= date_label(item) %><%= item.title.html_safe %>
      <% else %>
### <%= item.title.html_safe %>
      <% end %><%= "(#{item.author})".html_safe if include_authors && item.author.present? %>
      <% if item.description.present? %>

<%= item.description.html_safe %>
      <% end %>

    <% end %>

  <% end %>
<% end %>

app/views/items/_date_picker.html.erb
<div class='block'>
  <%= f.text_field :date,
    value: item.date,
    "data-date-format" => "yyyy-mm-dd",
    :size => nil,
    :class => "wide",
    'aria-label' => 'Date'
  %>
</div>

app/views/items/_item.html.erb
    <div class="block item">

      <% if item.author.present? %>
          <div class="author"><%= "#{item.author}" %></div>
      <% end %>

      <div class="title">
        <%= date_label(item) %><%= item.title %>
      </div>

      <div class="description collapse" id="item_<%= item.id %>">
        <%= raw GitHub::Markdown.render_gfm(item.description) %>
      </div>

      <div class="tools">
        <%= link_to edit_item_path(item) do %>
            <i class="icon-edit"></i>
        <% end %>
        <%= link_to item, data: { confirm: 'Are you sure?' }, method: :delete do %>
            <i class='icon-trash'></i>
        <% end %>
        <% if item.description.present? %>
            <a data-toggle="collapse" data-target="#item_<%= item.id %>">
              <i class="icon-info-sign"></i>
            </a>
        <% end %>
      </div>
    </div>

app/views/items/_presentation_item.html.erb
<li>
  <%= format_title(presentation_item) %>
  <% if presentation_item.author.present? %>
      <%= "(#{ presentation_item.author })" %>
  <% end %>
  <% if presentation_item.description.present? %>
      <a data-toggle="collapse" data-target="#item_<%= presentation_item.id %>">
        <i class="icon-info-sign"></i>
      </a>
      <div class="block description collapse" id="item_<%= presentation_item.id %>">
        <%= raw GitHub::Markdown.render_gfm(presentation_item.description) %>
      </div>
  <% end %>
</li>

app/views/items/index.html.erb
<div class="content-wrapper site-container">
  <div class="site-body">
    <%= render partial: 'as_html', locals: {items: @items} %>
  </div>

  <div class='bottom border-top'>
    <div class='navbar-inner'>
      <%= link_to 'Presentation', presentation_standup_items_path(@standup), class: 'btn btn-success navbar-btn' %>
      <%= form_tag "/standups/#{@standup.id}/posts", method: 'post', class: 'navbar-form pull-right' do %>
          <%= text_field_tag 'post[from]', nil, placeholder: 'Blogger Name(s)' %>
          <%= text_field_tag 'post[title]', nil, placeholder: 'Post Title (eg: Best Standup Ever)', class: 'wide-input' %>
          <%= submit_tag 'Create Post',
                         data: {confirm: 'This will clear the board and create a new one for tomorrow, you can always get back to this post under the "Posts" menu in the header. Continue?'},
                         id: 'create-post',
                         class: 'btn btn-warning'
          %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="content-wrapper">
  <%= form_for(@item, html: {class: 'form-horizontal item-form'}) do |f| %>
    <%= render partial: 'shared/errors', locals: {model: @item} %>

    <%= hidden_field_tag :redirect_to, params[:redirect_to] || request.referer %>

    <div class="block">
      <div class="btn-group btn-block" data-toggle-name="item[kind]" data-toggle="buttons-radio">
        <% (Item.kinds.map(&:name) - ['New face']).each do |kind| %>
          <button type='button' value='<%= kind %>' class='btn btn-info' data-toggle="button">
            <%= kind %>
          </button>
        <% end %>
      </div>
    </div>

    <div class="block with-hint">
      <div class="btn-group btn-block" data-toggle-name="item[public]" data-toggle="buttons-radio">
        <button type="button" value="0" class="btn btn-warning" data-toggle="button">
          Private
        </button>
        <button type="button" value="1" class="btn btn-warning" data-toggle="button">
          Post to Blog
        </button>
      </div>
      <div class="hint">
        <div>Private items are not posted to the Blog.</div>
        <div>All items are visible to anyone on Pivotal's Guest network.</div>
        <div>Do not post confidential information.</div>
      </div>
      <%= f.hidden_field :public, value: @item.public ? '1' : '0' %>
    </div>

    <div class="block">
      <%= f.collection_select(:standup_id,
        Standup.all,
        :id,
        :title,
        {},
        {:class => "wide",
          "aria-label" => "Standup"}) %>
    </div>

    <div class="block">
      <%= f.text_field :title, placeholder: "Item Title", size: nil, class: "wide" %>
    </div>

    <div class="block">
      <%= f.text_field :author, placeholder: "Author", size: nil, class: "wide" %>
    </div>

    <%= render partial: 'date_picker', locals: {f: f, item: @item} %>

    <div class="block has-bottom-border">
      <%= f.text_area :description, placeholder: markdown_placeholder, rows: 5, cols: nil, class: "wide" %>
    </div>

    <%= f.hidden_field :post_id %>
    <%= f.hidden_field :kind %>

    <div class="block">
      <%= f.submit nil, class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
</div>

app/views/items/new_new_face.html.erb
<div class="content-wrapper">
  <%= form_for(@item, html: {class: 'form-horizontal new-face-form'}) do |f| %>
    <%= render partial: 'shared/errors', locals: {model: @item} %>

    <div class="block header">
      <h2>New Face</h2>
    </div>

    <div class="block">
      <%= f.collection_select(:standup_id,
        Standup.all,
        :id,
        :title,
        {},
        {:class => "wide",
          "aria-label" => "Standup"}) %>
    </div>

    <div class="block with-hint">
      <%= f.text_field :title, placeholder: 'John Smith - Interviewing with Rob', class: "wide" %>
      <div class="hint always">
        Including why they are in the office makes for a much friendly welcome, e.g. Interviewing, New Pivot or Client
        Developer.
      </div>
    </div>

    <%= render partial: 'date_picker', locals: {f: f, item: @item} %>

    <%= f.hidden_field :post_id %>
    <%= f.hidden_field :public, value: false %>
    <%= f.hidden_field :kind, value: 'New face' %>

    <div class="block">
      <%= f.submit "#{@item.persisted? ? "Update" : "Create"} New Face", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/items/presentation.html.erb
  <section class="slide">
    <h1>
      Standup<br/>
      <span><%= @standup.date_today.strftime("%m/%d/%y") %></span>

      <div class="countdown">
        <% if @standup.finished_today %>
          starts NOW!
        <% else %>
          <span data-countdown-date="<%= @standup.next_standup_date.to_i * 1000 %>"></span>
        <% end %>
      </div>
    </h1>

    <div class='footer'>
      <p>
        <%= link_to 'Exit', standup_items_path(@standup), class: 'btn btn-large btn-primary exit-presentation' %>
      </p>
    </div>
  </section>

  <% Item.kinds.each do |kind| %>
    <% next if kind.name == 'Win' && !@items[kind.name].present? %>
    <section class="slide">
      <div class="titles">
        <h2><%= kind.name.pluralize %></h2>
      </div>
      <% if @items[kind.name] %>
        <% if kind.name == 'Event' || kind.name == 'New face' %>
          <% @items[kind.name].group_by(&:relative_date).each do |group_name, events| %>
            <h3 class="<%= group_name %>"><%= group_name.capitalize %></h3>
            <ul>
              <%= render partial: 'presentation_item', collection: events %>
            </ul>
          <% end %>
        <% else %>
          <ul>
            <%= render partial: 'presentation_item', collection: @items[kind.name] %>
          </ul>
        <% end %>
      <% end %>
      <div class='footer'>
        <p>
          <%= link_to 'Exit', standup_items_path(@standup), class: 'btn btn-large btn-primary exit-presentation' %>
        </p>
      </div>
    </section>
  <% end %>

  <section class="slide">
    <h1><%= @standup.closing_message %>
      <% if @standup.image_urls %>
        <%= image_tag(@standup.closing_image) %>
      <% end %>
    </h1>

    <div class='footer'>
      <p>
        <%= link_to 'Exit', standup_items_path(@standup), class: 'btn btn-large btn-primary exit-presentation' %>
      </p>
    </div>
  </section>