config/routes.rb
Whiteboard::Application.routes.draw do
  resources :items, only: :create
  resources :sessions, only: [:create, :destroy]

  resources :standups, shallow: true do
    resources :items, only: :new
    resources :items do
      collection do
        get 'presentation'
      end
    end

    resources :posts do
      member do
        put 'send_email'
        put 'post_to_blog'
        put 'archive'
      end

      collection do
        get 'archived'
      end

    end
  end

  match '/auth/saml/callback', to: 'sessions#create', via: [:get, :post]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  root to: 'standups#last_or_index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :standup

  has_many :items
  has_many :public_items, -> { where public: true }, class_name: "Item"

  validates :standup, presence: true
  validates :title, presence: true

  attr_accessible :title, :from

  delegate :subject_prefix, to: :standup, prefix: :standup

  def self.pending
    where(archived: false)
  end

  def self.archived
    where(archived: true)
  end

  def adopt_all_the_items
    self.items = Item.for_post(standup)
  end

  def title_for_email
    if standup_subject_prefix.present?
      "#{standup_subject_prefix} " + title_for_blog
    else
      "[Standup] " + title_for_blog
    end
  end

  def title_for_blog
    created_at.strftime("%m/%d/%y") + ': '+ title
  end

  def events
    Item.events_on_or_after(Time.zone.today, standup)
  end

  def public_events
    Item.public.events_on_or_after(Time.zone.today, standup)
  end

  def items_by_type
    sorted_by_type(items).merge(events) { |key, old, new| old + new }
  end

  def public_items_by_type
    sorted_by_type(public_items).merge(public_events)
  end

  def deliver_email
    if sent_at
      raise "Duplicate Email"
    else
      PostMailer.send_to_all(self, standup.to_address, 'noreply@pivotal.io', standup.id).deliver
      self.sent_at = Time.now
      self.save!
    end
  end

  def publishable_content?
    public_items.present? || public_events.present?
  end

  def emailable_content?
    items.present? || events.present?
  end

  def public_url
    if Rails.application.config.blogging_service.minimally_configured? and blog_post_id.present?
      Rails.application.config.blogging_service.public_url + "/#{blog_post_id}"
    else
      ''
    end
  end

  private

  def sorted_by_type(relation)
    relation.order("created_at ASC").group_by(&:kind)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_post, except: [:create, :index, :archived]
  before_filter :load_standup
  around_filter :standup_timezone


  def create
    @standup = Standup.find_by_id(params[:standup_id])
    @post = @standup.posts.build(params[:post])
    if @post.save
      @post.adopt_all_the_items
      redirect_to edit_post_path(@post)
    else
      flash[:error] = "Unable to create post"
      redirect_to @standup
    end
  end

  def update
    @post.update_attributes(params[:post])
    if @post.save
      redirect_to edit_post_path(@post)
    else
      render 'posts/edit'
    end
  end

  def edit
  end

  def index
    @posts = @standup.posts.pending
  end

  def archived
    @posts = @standup.posts.archived
  end

  def send_email
    if @post.sent_at
      flash[:error] = "The post has already been emailed"
    else
      @post.deliver_email
    end
    redirect_to edit_post_path(@post)
  end

  def post_to_blog
    if @post.blogged_at
      flash[:error] = "The post has already been blogged"
    elsif !view_context.wordpress_enabled?
      flash[:error] = "Wordpress blogging disabled. Please set wordpress environment variables."
    else
      blog_post = BlogPost.new.tap do |blog_post|
        blog_post.title = @post.title
        blog_post.body = prepare_post_body(@post.public_items_by_type)
      end

      begin
        @post.blog_post_id = Rails.configuration.blogging_service.send!(blog_post)
        @post.blogged_at = Time.now
        @post.save!
      rescue XMLRPC::FaultException => e
        message = "While posting to the blog, the service reported the following error: '" + e.message + "', please repost."
        flash[:error] = message
      end

    end

    redirect_to edit_post_path(@post)
  end

  def archive
    @post.archived = true
    @post.save!
    redirect_to @post.standup
  end

  private

  def load_post
    @post = Post.find_by_id(params[:id])
    @standup = @post.standup if @post.present?
    head 404 unless @post
  end

  def load_standup
    if params[:standup_id].present?
      @standup = Standup.find_by(id: params[:standup_id])
    else
      @standup = Post.find(params[:id]).standup
    end
  end

  def prepare_post_body(items)
    GitHub::Markdown.render(
      render_to_string(partial: 'items/as_markdown',
                       formats: [:text],
                       layout: false,
                       locals: {items: items, include_authors: false}))
  end


  def standup_timezone(&block)
    return yield unless @standup
    Time.use_zone(@standup.time_zone_name, &block)
  end
end

app/views/posts/_table.html.erb
<table class='table table-striped table-hover'>
  <tr>
    <th class="col-sm-6">Post Name</th>
    <th class="col-sm-3">From</th>
    <th class="col-sm-3">Creation Date</th>
  </tr>
  <% posts.each do |post| %>
    <tr>
      <td class="col-sm-6"><%= link_to post.title, show_or_edit_post_path(post) %></td>
      <td class="col-sm-3"><%= post.from %></td>
      <td class="col-sm-3"><%= post.created_at.strftime('%Y-%m-%d %H:%M:%S') %> UTC</td>
    </tr>
<% end %>
</table>

app/views/posts/archived.html.erb
<div class="content-wrapper">
  <h2>Archived Posts</h2>

  <%= render partial: 'table', locals: {posts: @posts} %>
</div>

app/views/posts/edit.html.erb
<div class="content-wrapper">
  <h1>Review</h1>

  <div class='well'>
    <h3>Please update these items with any new information from standup:</h3>

    <div>
      Add any answers/discussions that were brought up. <strong>If you missed anything, ask the owner of the help /
      interesting to fill in details before you submit.</strong>
    </div>

    <%= render partial: 'items/as_html', locals: {items: @post.items_by_type} %>

    <hr>
    <div>
      <h3>Update the author(s) and title if necessary:</h3>
      <%= form_for(@post, html: {class: 'form-inline'}) do |f| %>
          <%= render partial: 'shared/errors',  locals: {model: @post} %>

          <%= f.text_field :from, :'aria-label' => 'From' %>
          <%= f.text_field :title, :'aria-label' => 'Title' %>
          <%= f.submit "Update", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <h1>Publish</h1>

  <div class='well' id='publish'>
    <h3>Please double check this email for accuracy. When you are ready, press the 'send email now' button:</h3>

    <div class='email_post preview'>
      <pre>
Subject: <%= @post.title_for_email %>
        From: <%= @post.from %>

        <%= raw CGI::escapeHTML(GitHub::Markdown.render(render partial: 'items/as_markdown', formats: [:text], handlers: [:erb], locals: {items: @post.items_by_type, include_authors: true})) %>
  </pre>
    </div>

    <% if @post.sent_at %>
        This email was sent at <%= @post.sent_at %>
    <% elsif @post.emailable_content? %>
        <%= link_to 'Send Email', send_email_post_path(@post),
                    data: {confirm: 'Emails can not be unsent.  Are you sure?'},
                    method: :put,
                    class: 'btn btn-warning' %>
    <% else %>
        <p class='btn btn-warning' disabled='disabled'>Send Email</p>
        <span class='notice'>There is no content to publish.</span>
    <% end %>
    <br/>
    <br/>

    <h3>Please double check the blog post. Ensure that there are no client names or private info in the post, and that
      the content is of interest to the general public. Click the "Post Blog Entry" button to post it to
      <%= link_to Rails.application.config.blogging_service.public_url, Rails.application.config.blogging_service.public_url %>.</h3>

    <div class='blog_post preview'>
      (Title: <%= @post.title_for_blog %>)

  <pre>
<%= raw CGI::escapeHTML(GitHub::Markdown.render(render partial: 'items/as_markdown', formats: [:text], handlers: [:erb], locals: {items: @post.public_items_by_type, include_authors: false})) %>
  </pre>
    </div>
    <% if @post.blogged_at %>
        <%= published_post_info(@post) %>
    <% elsif !@post.publishable_content? %>
        <p class='btn btn-warning' disabled='disabled'>Post Blog Entry</p>
        <span class='notice'>There is no content to publish; please verify that the helps / interestings are marked as public if you want to include them in the blog post.</span>
    <% elsif wordpress_enabled? %>
        <%= link_to 'Post Blog Entry', post_to_blog_post_path(@post),
                    data: {confirm: 'This will post to wordpress.  Are you sure?'},
                    method: :put,
                    class: 'btn btn-warning' %>
    <% elsif !wordpress_enabled? %>
        <p class='btn btn-warning' disabled='disabled' title='Wordpress is not configured. You can not send blog posts.'>Post
          Blog Entry</p>
    <% end %>
  </div>

  <h1>Archive</h1>

  <div class='well'>
    <h3> Thanks for emailing and blogging. Click the button below to archive the post.</h3>
    <%= link_to 'Archive Post', archive_post_path(@post), method: :put, class: 'btn btn-warning' %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="content-wrapper">
  <h2>Pending Posts</h2>

  <%= render partial: 'table', locals: {posts: @posts} %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<% items = @post.items_by_type %>
<% Item.kinds.map(&:name).each do |kindName| %>
  <% if items[kindName] %>
    <h2><%= kindName.pluralize %></h2>
    <ul>
        <% items[kindName].each do |item| %>
        <li><%=  item.title %></li>
        <% if item.description.present? %>
          <pre><%=  item.description %></pre>
        <% end %>
        <% if item.author.present? %>
          <pre>(<%=  item.author %>)</pre>
        <% end %>
      <% end %>
    </ul>
  <% end %>
<% end %>